import "../styles/global.css";
import StyledComponentsRegistry from "../lib/registry";

export const metadata = {
  title: "GPTQuizHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
